<?php

use Illuminate\Database\Seeder;
use App\Models\Battery;

class BatterySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Amaron
        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 1,
            'type_id' => 2,
            'trade_in_id' => 1,
            'model' => '38B20L',
            'model_reference' => 'NS40',
            'price' => '220',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 35,
            'cca' => 265,
            'rc' => 43,
            'length' => 197,
            'width' => 129,
            'height' => 227,
            'image' => 'Amaron_38B20L_image.png',
            'image_size' => 664576,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 1,
            'model' => '42B20L',
            'model_reference' => 'NS40',
            'price' => '240',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 35,
            'cca' => 335,
            'rc' => 55,
            'length' => 197,
            'width' => 129,
            'height' => 227,
            'image' => 'Amaron_42B20L_image.png',
            'image_size' => 791540,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 1,
            'type_id' => 2,
            'trade_in_id' => 2,
            'model' => '46B24L',
            'model_reference' => 'NS60',
            'price' => '250',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 45,
            'cca' => 295,
            'rc' => 56,
            'length' => 238,
            'width' => 128,
            'height' => 227,
            'image' => 'Amaron_46B24LR_image.png',
            'image_size' => 1134927,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 1,
            'type_id' => 2,
            'trade_in_id' => 2,
            'model' => '46B24R',
            'model_reference' => 'NS60',
            'price' => '250',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 45,
            'cca' => 295,
            'rc' => 56,
            'length' => 238,
            'width' => 128,
            'height' => 227,
            'image' => 'Amaron_46B24LR_image.png',
            'image_size' => 1134927,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 2,
            'model' => '55B24L',
            'model_reference' => 'NS60',
            'price' => '300',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 45,
            'cca' => 380,
            'rc' => 75,
            'length' => 238,
            'width' => 128,
            'height' => 227,
            'image' => 'Amaron_55B24LR_image.png',
            'image_size' => 335399,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 2,
            'model' => '55B24R',
            'model_reference' => 'NS60',
            'price' => '300',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 45,
            'cca' => 380,
            'rc' => 75,
            'length' => 238,
            'width' => 128,
            'height' => 227,
            'image' => 'Amaron_55B24LR_image.png',
            'image_size' => 335399,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 1,
            'type_id' => 2,
            'trade_in_id' => 2,
            'model' => '55D23L',
            'model_reference' => '',
            'price' => '350',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 60,
            'cca' => 320,
            'rc' => 74,
            'length' => 232,
            'width' => 173,
            'height' => 225,
            'image' => 'Amaron_55D23L_image.png',
            'image_size' => 1217390,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 3,
            'model' => '65D26L',
            'model_reference' => '',
            'price' => '350',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 50,
            'cca' => 420,
            'rc' => 90,
            'length' => 260,
            'width' => 173,
            'height' => 225,
            'image' => 'Amaron_65D26LR_image.png',
            'image_size' => 514423,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 3,
            'model' => '65D26R',
            'model_reference' => '',
            'price' => '350',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 50,
            'cca' => 420,
            'rc' => 90,
            'length' => 260,
            'width' => 173,
            'height' => 225,
            'image' => 'Amaron_65D26LR_image.png',
            'image_size' => 514423,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 4,
            'model' => '95D31L',
            'model_reference' => '',
            'price' => '380',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 70,
            'cca' => 600,
            'rc' => 120,
            'length' => 306,
            'width' => 173,
            'height' => 225,
            'image' => 'Amaron_95D31LR_image.png',
            'image_size' => 664576,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 2,
            'type_id' => 2,
            'trade_in_id' => 4,
            'model' => '95D31R',
            'model_reference' => '',
            'price' => '380',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 70,
            'cca' => 600,
            'rc' => 120,
            'length' => 306,
            'width' => 173,
            'height' => 225,
            'image' => 'Amaron_95D31LR_image.png',
            'image_size' => 664576,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 3,
            'type_id' => 2,
            'trade_in_id' => 3,
            'model' => 'DIN55',
            'model_reference' => '',
            'price' => '350',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 55,
            'cca' => 500,
            'rc' => 120,
            'length' => 242,
            'width' => 175,
            'height' => 190,
            'image' => 'Amaron_DIN55_image.png',
            'image_size' => 687213,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 3,
            'type_id' => 2,
            'trade_in_id' => 3,
            'model' => 'DIN66',
            'model_reference' => '',
            'price' => '480',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 66,
            'cca' => 610,
            'rc' => 121,
            'length' => 242,
            'width' => 175,
            'height' => 190,
            'image' => 'Amaron_DIN66_image.png',
            'image_size' => 687213,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 3,
            'type_id' => 2,
            'trade_in_id' => 4,
            'model' => 'DIN80',
            'model_reference' => '',
            'price' => '580',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 80,
            'cca' => 730,
            'rc' => 121,
            'length' => 375,
            'width' => 175,
            'height' => 175,
            'image' => 'Amaron_DIN80_image.png',
            'image_size' => 687213,
            'description' => '',
            'specifications' => '{}',
        ]);

        Battery::create([
            'manufacturer_id' => 1,
            'series_id' => 3,
            'type_id' => 2,
            'trade_in_id' => 5,
            'model' => 'DIN100',
            'model_reference' => '',
            'price' => '680',
            'warranty' => 18,
            'stock' => 1,
            'volt' => 12,
            'ah' => 100,
            'cca' => 900,
            'rc' => 121,
            'length' => 353,
            'width' => 175,
            'height' => 190,
            'image' => 'Amaron_DIN100_image.png',
            'image_size' => 687213,
            'description' => '',
            'specifications' => '{}',
        ]);
    }
}
